server:
  port: 9392
spring:
  application:
    name: MOVIE-SERVICEs

logging:
  file:
    name: C:Users/reece/Desktop/logs/microservices.log
#    hostname: localhost
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost